# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'likeMap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for likeMap

   pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'

end

target 'likeMap-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for likeMap-tvOS

  target 'likeMap-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
